const {chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
  fs.mkdirSync('/workspace/cmestudios-dotacion/artifacts',{recursive:true});
  const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
  const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:5173',{waitUntil:'networkidle'});
  await page.screenshot({path:'/workspace/cmestudios-dotacion/artifacts/dashboard.png',fullPage:true});
  assert.match(await page.locator('.kpis').first().innerText(),/1\.100/);
  const initial=await page.evaluate(()=>JSON.parse(localStorage.getItem('cmestudios.dotacion.demo.v1')));
  assert.equal(initial.staff.length,2200);
  await page.getByRole('button',{name:'Importar datos',exact:true}).click();
  await page.getByRole('button',{name:'Probar archivo de ejemplo'}).click();
  assert.match(await page.locator('.mini-summary').innerText(),/2.*nuevos/s);
  await page.getByRole('button',{name:'Confirmar importación'}).click();
  await page.getByRole('heading',{name:'Datos incorporados'}).waitFor();
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cmestudios.dotacion.demo.v1')).staff.length),2202);
  await page.getByRole('button',{name:'Revisar dotación',exact:true}).click();
  await page.getByRole('textbox',{name:'Buscar persona, cargo o establecimiento'}).fill('IMPORT-0001');
  await page.getByRole('button',{name:'Editar IMPORT-0001',exact:true}).click();
  await page.getByLabel('Lectivas asignadas (45 min)').fill('28');
  await page.getByLabel('Justificación del ajuste').fill('Ajuste de matrícula en el escenario de prueba');
  await page.getByRole('button',{name:'Guardar y recalcular'}).click();
  const updated=await page.evaluate(()=>JSON.parse(localStorage.getItem('cmestudios.dotacion.demo.v1')).staff.find(p=>p.id==='IMPORT-0001'));
  assert.equal(updated.assignedPed,28);assert.match(await page.locator('tbody').innerText(),/Sobrecarga/);
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cmestudios.dotacion.demo.v1')).staff.find(p=>p.id==='IMPORT-0001').assignedPed),28);
  await page.getByRole('button',{name:'Planes y cuadratura',exact:true}).click();
  await page.getByRole('combobox',{name:'Establecimiento para cuadratura'}).selectOption('EST-002');
  const before=await page.locator('.plan-kpis .kpi').first().locator(':scope > strong').innerText();
  await page.getByRole('button',{name:'Editar',exact:true}).first().click();
  await page.getByLabel('Horas pedagógicas por curso').fill('10');
  await page.getByLabel('Justificación',{exact:true}).fill('Nueva carga curricular ficticia');
  await page.getByRole('button',{name:'Guardar y recalcular'}).click();
  const after=await page.locator('.plan-kpis .kpi').first().locator(':scope > strong').innerText();assert.notEqual(before,after);
  await page.getByRole('combobox',{name:'Establecimiento para cuadratura'}).selectOption('EST-039');
  await page.getByRole('button',{name:'Configurar',exact:true}).click();
  await page.getByLabel('Niños por educadora (escenario)').fill('10');
  await page.getByLabel('Niños por técnica (escenario)').fill('7');
  await page.getByLabel('Justificación técnico-pedagógica').fill('Prueba de coeficientes ficticios; no valores legales');
  await page.getByRole('button',{name:'Guardar parámetros'}).click();
  await page.getByRole('heading',{name:'Escenario de coeficientes activo'}).waitFor();
  await page.getByRole('combobox',{name:'Establecimiento para cuadratura'}).selectOption('EST-026');
  assert.match(await page.locator('main').innerText(),/especialidad técnico-profesional/);
  await page.getByRole('combobox',{name:'Establecimiento para cuadratura'}).selectOption('EST-053');
  assert.match(await page.locator('main').innerText(),/6 escuelas rurales/);
  for(const [name,extension] of [['CSV','.csv'],['Excel','.xlsx'],['PDF','.pdf']]){
    const event=page.waitForEvent('download');await page.getByRole('button',{name,exact:true}).click();const download=await event;assert.ok(download.suggestedFilename().endsWith(extension));await download.saveAs('/workspace/cmestudios-dotacion/artifacts/'+download.suggestedFilename());
  }
  await page.getByRole('button',{name:'Importar datos',exact:true}).click();
  await page.getByLabel('Archivo CSV del maestro').setInputFiles({name:'invalid.csv',mimeType:'text/csv',buffer:Buffer.from('id;nombre\n1;Demo')});
  await page.getByText('No se aplicó ningún cambio.').waitFor();assert.equal(await page.getByRole('button',{name:'Confirmar importación'}).isDisabled(),true);
  await page.getByRole('button',{name:'Bitácora de cambios',exact:true}).click();assert.match(await page.locator('.timeline').innerText(),/Maestro CSV importado/);
  await page.getByRole('combobox',{name:'Vista de demostración'}).selectOption('school');
  await page.getByRole('combobox',{name:'Establecimiento de la vista demo'}).selectOption('EST-002');
  await page.getByRole('button',{name:'Dotación',exact:true}).click();assert.match(await page.locator('tbody').innerText(),/Horizonte del Sur/);assert.doesNotMatch(await page.locator('tbody').innerText(),/Lago Llanquihue/);
  await page.getByRole('combobox',{name:'Vista de demostración'}).selectOption('all');
  await page.getByRole('button',{name:'Vista general',exact:true}).click();
  await page.screenshot({path:'/workspace/cmestudios-dotacion/artifacts/dashboard-after.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/workspace/cmestudios-dotacion/artifacts/mobile.png',fullPage:true,animations:'disabled'});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile document overflow');
  assert.deepEqual(errors,[]);
  console.log('PASS: rendering, CSV preview/upsert/errors, editable staff/plans, recalculation, VTF, TP, microcenters, CSV/XLSX/PDF downloads, persistence, scoped view and mobile.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
