import React, { useEffect, useMemo, useRef, useState } from 'react';
import { LayoutDashboard, School, UsersRound, BookOpen, UploadCloud, History, ChevronDown, ChevronUp, ArrowUpRight, ArrowRight, Search, Bell, Download, Plus, Check, X, CheckCircle2, AlertTriangle, Building2, SlidersHorizontal, FileSpreadsheet, FileText, Pencil, RotateCcw, ShieldCheck, CircleHelp, ArrowLeft, GraduationCap, Sprout, Layers, Clock3, Menu, BriefcaseBusiness, TrendingUp, ArrowLeftRight } from 'lucide-react';
import { MODALITIES, STORAGE_KEY, fmt, round, capacityPedagogical, teacherCheck, summarizeSchool, createSeed, serializeCSV, parseCSV, validateImport, applyImport, sampleImport, movableTeachers, suggestReassignments, applyReassignments } from './core.mjs';

const NAV = [ ['overview', 'Vista general', LayoutDashboard], ['schools', 'Establecimientos', School], ['people', 'Dotación', UsersRound], ['plans', 'Planes y cuadratura', BookOpen], ['reassign', 'Reasignación', ArrowLeftRight], ['import', 'Importar datos', UploadCloud], ['history', 'Bitácora de cambios', History] ];
const Titles = { overview: ['Tu planificación, en perspectiva.', 'Una visión clara de la dotación para el año escolar 2027.'], schools: ['Cada comunidad, su planificación.', 'Gestiona la dotación según la modalidad de cada establecimiento.'], people: ['Las personas detrás de cada aula.', 'Revisa jornadas, financiamiento y proyección del personal.'], plans: ['De las horas al equilibrio.', 'Cruza planes de estudio y horas asignadas, con unidades explícitas.'], reassign: ['De donde sobra, a donde falta.', 'Mueve docentes de establecimientos con excedente a otros con déficit y revisa el efecto antes de aplicar.'], import: ['Tus datos, en un solo lugar.', 'Importa el maestro de personal, valida y revisa antes de incorporar.'], history: ['Cada decisión deja una huella.', 'Consulta los cambios realizados en este escenario de demostración.'] };
const Status = ({ value }) => <span className={`badge ${value === 'Equilibrado' ? 'green' : value === 'Excedente' ? 'blue' : value === 'Por validar' ? 'neutral' : 'amber'}`}><span className="status-dot" />{value}</span>;
const ModeIcon = ({ mode, size = 18 }) => { const Icon = mode === 'Jardín VTF' ? Sprout : mode === 'Microcentro' ? Layers : mode === 'Técnico profesional' ? BriefcaseBusiness : GraduationCap; return <Icon size={size} />; };
function getInitial() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); if (saved?.version === 1 && Array.isArray(saved.schools) && Array.isArray(saved.staff) && Array.isArray(saved.plans) && Array.isArray(saved.events)) return saved; } catch {} return createSeed(); }
function saveDownload(name, content, type = 'text/csv;charset=utf-8') { const a = document.createElement('a'); const url = URL.createObjectURL(new Blob([content], {type})); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function Dialog({ title, subtitle, children, close, wide = false }) {
  const ref = useRef(); const previous = useRef(document.activeElement);
  useEffect(() => { const el = ref.current; el.showModal(); return () => { if (el.open) el.close(); previous.current?.focus?.(); }; }, []);
  return <dialog ref={ref} className={`dialog ${wide ? 'wide' : ''}`} onCancel={e => {e.preventDefault();close();}} onClick={e => {if(e.target === ref.current)close();}}><header><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div><button className="icon-btn" aria-label="Cerrar" onClick={close}><X size={20}/></button></header>{children}</dialog>;
}

export default function App() {
  const [state, setState] = useState(getInitial);
  const [page, setPage] = useState('overview');
  const [scope, setScope] = useState('all');
  const [selectedSchool, setSelectedSchool] = useState('EST-001');
  const [query, setQuery] = useState('');
  const [modality, setModality] = useState('Todas las modalidades');
  const [personType, setPersonType] = useState('Todo el personal');
  const [personPage, setPersonPage] = useState(1);
  const [modal, setModal] = useState(null);
  const [notice, setNotice] = useState('');
  const [storageError, setStorageError] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [busy, setBusy] = useState(false);
  useEffect(() => { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); setStorageError(false); } catch { setStorageError(true); } }, [state]);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 5000); return () => clearTimeout(timer); }, [notice]);
  useEffect(() => { setPersonPage(1); }, [query, modality, personType, scope, selectedSchool]);
  const stats = useMemo(() => state.schools.map(s => summarizeSchool(s, state.staff, state.plans)), [state]);
  const scoped = scope === 'all' ? stats : stats.filter(s => s.id === selectedSchool);
  const visibleSchools = scoped.filter(s => (modality === 'Todas las modalidades' || s.modality === modality) && `${s.name} ${s.commune} ${s.id}`.toLowerCase().includes(query.toLowerCase()));
  const ids = new Set(scoped.map(s => s.id));
  const people = state.staff.filter(p => ids.has(p.schoolId));
  const school = state.schools.find(s => s.id === selectedSchool) || state.schools[0];
  const summary = stats.find(s => s.id === school.id);
  const teachers = people.filter(p => p.type === 'Docente');
  const assistants = people.filter(p => p.type === 'Asistente');
  const deficits = scoped.filter(s => s.status === 'Déficit');
  const overloads = scoped.reduce((s, x) => s + x.overloads, 0);
  const hours = teachers.reduce((s, p) => s + p.contractHours, 0);
  const events = [...state.events].reverse();
  const modalityCounts = [0,0,0,0];
  for (const p of people) {
    const m = state.schools.find(s=>s.id===p.schoolId)?.modality;
    modalityCounts[m==='Escuela regular'?0:['Liceo','Técnico profesional'].includes(m)?1:m==='Jardín VTF'?2:3]++;
  }
  let angle = 0;
  const donutGradient = `conic-gradient(${modalityCounts.map((n,i)=>{const from=angle;angle += people.length?n/people.length*100:0;return `${['#5f4be1','#a18be9','#d2c6ee','#b3cce9'][i]} ${from}% ${angle}%`;}).join(', ')})`;

  const changePage = next => { setPage(next);setQuery('');setModality('Todas las modalidades');setMobileNav(false); };
  const commit = (next, action, detail) => {
    const event = { id: crypto.randomUUID(), date: new Date().toISOString(), author: 'Administrador · Demo', action, detail };
    setState(prev => ({ ...(typeof next === 'function' ? next(prev) : next), events: [...prev.events, event] }));
  };
  const goPlan = id => {setSelectedSchool(id);changePage('plans');};
  const goPeople = id => { if (scope === 'all') {setScope('school');setSelectedSchool(id);} changePage('people'); };
  const reportRows = () => page === 'people' ? filteredPeople.map(p => ({ID:p.id, Nombre:p.name, Establecimiento:state.schools.find(s=>s.id===p.schoolId)?.name, Tipo:p.type, Cargo:p.role, Horas_contrato_cronologicas:p.contractHours, Horas_lectivas_pedagogicas:p.assignedPed, Financiamiento:p.funding, Proyeccion:p.projection})) : page === 'plans' ? (school.modality === 'Jardín VTF' ? [{ Establecimiento:school.name, Matricula:school.enrollment, Educadoras:summary.educators, Tecnicas:summary.technicians, Coeficiente_educadora:school.educatorPerChildren ?? 'Pendiente de validar', Coeficiente_tecnica:school.technicianPerChildren ?? 'Pendiente de validar', Estado:summary.status }] : state.plans.filter(p=>p.schoolId===school.id).map(p=>({Establecimiento:school.name, Asignatura:p.subject, Cursos:p.groups, Horas_pedagogicas_por_curso:p.hoursPerGroup, Horas_pedagogicas_totales:p.groups*p.hoursPerGroup}))) : visibleSchools.map(s=>({ID:s.id, Establecimiento:s.name, Modalidad:s.modality, Comuna:s.commune, Docentes:s.teachers, Asistentes:s.assistants, Horas_requeridas_pedagogicas:s.modality==='Jardín VTF'?'No aplica':s.required, Horas_asignadas_pedagogicas:s.modality==='Jardín VTF'?'No aplica':s.assigned, Diferencia_pedagogica:s.modality==='Jardín VTF'?'No aplica':s.gap, Estado:s.status, Proyeccion:s.projection, Justificacion:s.justification}));
  const exportReport = async format => {
    setBusy(true);
    try {
      const rows = reportRows();
      if (!rows.length) { setNotice('No hay resultados para exportar.'); return; }
      if (format === 'csv') saveDownload(`dotacion-2027-${page}.csv`, serializeCSV(rows));
      if (format === 'xlsx') { const XLSX = await import('xlsx'); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(rows), 'Dotacion 2027'); XLSX.writeFile(wb, `dotacion-2027-${page}.xlsx`); }
      if (format === 'pdf') {
        const {jsPDF} = await import('jspdf');const {autoTable} = await import('jspdf-autotable'); const pdf = new jsPDF({orientation:'landscape'});
        pdf.setFontSize(18); pdf.text('CMEstudios | Dotacion 2027',14,18);pdf.setFontSize(9);pdf.text('DEMOSTRACION - Datos ficticios. Formato propio; pendiente adaptar a layouts MINEDUC/DEP.',14,25);
        autoTable(pdf,{head:[Object.keys(rows[0]).map(k=>k.replaceAll('_',' '))],body:rows.map(r=>Object.values(r)),startY:32,styles:{fontSize:7},headStyles:{fillColor:[24,79,67]},didDrawPage:()=>{pdf.setFontSize(8);pdf.text('Escenario demo | '+new Date().toLocaleDateString('es-CL'),14,pdf.internal.pageSize.height-8);}});pdf.save(`dotacion-2027-${page}.pdf`);
      }
      setNotice(`Reporte ${format.toUpperCase()} descargado.`);
    } catch {setNotice('No se pudo exportar el reporte. Intenta nuevamente.');} finally {setBusy(false);}
  };
  const exportIndividual = async person => {
    setBusy(true);
    try { const {jsPDF} = await import('jspdf');const {autoTable} = await import('jspdf-autotable'); const pdf=new jsPDF();const s=state.schools.find(x=>x.id===person.schoolId);const check=teacherCheck(person,s);
      pdf.setFontSize(19);pdf.text('Ficha individual de carga horaria',14,20);pdf.setFontSize(10);pdf.text('CMEstudios | DEMO 2027 - persona ficticia',14,29);pdf.text('Formato de demostracion, pendiente adaptar al formato MINEDUC.',14,36);
      autoTable(pdf,{startY:45,body:[['Persona',person.name],['ID ficticio',person.id],['Establecimiento',s.name],['Cargo',person.role],['Contrato',person.contract],['Financiamiento',person.funding],['Horas contrato (60 min)',person.contractHours],['Proporcion configurada',fmt(s.lectiveRatio*100)+'% / '+fmt((1-s.lectiveRatio)*100)+'%'],['Maximo lectivo configurado (60 min)',person.type==='Docente'?check.lectiveClock:'No aplica'],['Reserva no lectiva configurada (60 min)',person.type==='Docente'?check.nonLectiveClock:'No aplica'],['Lectivas asignadas (45 min)',person.assignedPed],['Proyeccion',person.projection],['Justificacion',person.justification||'Sin cambios registrados']],styles:{fontSize:10},columnStyles:{0:{fontStyle:'bold',cellWidth:85}},theme:'striped'});
      pdf.text('Firma de la persona: __________________________',14,Math.min(270,pdf.lastAutoTable.finalY+22));pdf.save(`carga-horaria-${person.id}.pdf`);setNotice('Ficha individual PDF descargada.');
    } catch {setNotice('No se pudo generar la ficha.');}finally{setBusy(false);}
  };
  const filteredPeople = people.filter(p => (personType === 'Todo el personal' || p.type === personType) && (modality === 'Todas las modalidades' || state.schools.find(s=>s.id===p.schoolId)?.modality===modality) && `${p.name} ${p.id} ${p.role} ${state.schools.find(s=>s.id===p.schoolId)?.name}`.toLowerCase().includes(query.toLowerCase()));
  const exportButtons = <div className="export-group"><button disabled={busy} onClick={()=>exportReport('csv')}><Download size={15}/>CSV</button><button disabled={busy} onClick={()=>exportReport('xlsx')}><FileSpreadsheet size={15}/>Excel</button><button disabled={busy} onClick={()=>exportReport('pdf')}><FileText size={15}/>PDF</button></div>;

  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav?'open':''}`}>
      <a className="brand" href="#" onClick={e=>{e.preventDefault();changePage('overview');}}><span className="brand-mark"><span/></span><div>CM<span>Estudios</span><small>GESTIÓN EDUCATIVA</small></div></a>
      <div className="workspace"><span className="workspace-icon"><Building2 size={18}/></span><div>SLEP Llanquihue<small>Escenario de demostración</small></div><ChevronDown size={15}/></div>
      <p className="nav-label">PLANIFICACIÓN</p>
      <nav>{NAV.map(([id,label,Icon])=><button key={id} aria-label={label} className={page===id?'active':''} onClick={()=>changePage(id)}><Icon size={19}/><span>{label}</span>{id==='import'&&<span className="nav-mini">CSV</span>}</button>)}</nav>
      <div className="sidebar-guide"><div className="guide-icon"><GraduationCap size={23}/></div><h3>Del dato a la decisión.</h3><p>Una dotación clara para planificar el próximo año escolar.</p><button onClick={()=>setModal({type:'guide'})}>Recorrido de la demo <ArrowUpRight size={15}/></button></div>
      <button className="sidebar-help" onClick={()=>setModal({type:'rules'})}><CircleHelp size={17}/> Alcance y reglas de cálculo</button>
      <div className="sidebar-user"><span className="avatar">CM</span><div>Equipo CMEstudios<small>Administrador · Demo local</small></div></div>
    </aside>
    <main>
      <header className="topbar"><div className="breadcrumb"><button className="icon-btn mobile-only" aria-label="Abrir menú" onClick={()=>setMobileNav(!mobileNav)}><Menu size={20}/></button><span>Planificación</span><span>/</span><strong>{NAV.find(n=>n[0]===page)[1]}</strong></div><div className="topbar-right"><span className="local-dot">Demo local · datos ficticios</span><button className="icon-btn notification" aria-label="Ver alertas" onClick={()=>setModal({type:'alerts'})}><Bell size={19}/><i/></button><span className="top-avatar">CM</span></div></header>
      <div className="content">
        {storageError&&<div className="warning-banner"><AlertTriangle size={17}/>El navegador no pudo guardar los cambios. Exporta los datos antes de cerrar.</div>}
        <div className="page-heading"><div><div className="eyebrow">DOTACIÓN ESCOLAR / 2027</div><h1>{Titles[page][0]}</h1><p>{Titles[page][1]}</p></div><div className="heading-actions"><span className="period-pill"><span/>Año escolar 2027</span><select aria-label="Vista de demostración" value={scope} onChange={e=>{setScope(e.target.value);setQuery('');}}><option value="all">Sostenedor · vista demo</option><option value="school">Establecimiento · vista demo</option></select></div></div>
        {scope==='school'&&<div className="scope-banner"><School size={18}/><span>Vista de establecimiento</span><select aria-label="Establecimiento de la vista demo" value={selectedSchool} onChange={e=>setSelectedSchool(e.target.value)}>{state.schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><small>Simulación de alcance; sin autenticación de producción.</small><button onClick={()=>setScope('all')}>Ver todo <X size={14}/></button></div>}

        {page==='overview'&&<>
          <section className="kpis"><Kpi icon={School} title={scope==='all'?'Establecimientos':'Unidad en vista'} value={scope==='all'?'52 + 4':scoped.length} footer={scope==='all'?'52 establecimientos y 4 microcentros':'Alcance de la vista seleccionada'} color="teal"/><Kpi icon={UsersRound} title="Dotación docente" value={fmt(teachers.length)} footer={`${fmt(hours)} horas cronológicas contratadas`} color="blue"/><Kpi icon={BriefcaseBusiness} title="Asistentes de la educación" value={fmt(assistants.length)} footer={`${fmt(assistants.reduce((a,p)=>a+p.contractHours,0))} horas cronológicas contratadas`} color="purple"/><Kpi icon={AlertTriangle} title="Brechas por revisar" value={fmt(deficits.length)} footer={`${overloads} sobrecargas individuales · ${scoped.filter(s=>s.status==='Por validar').length} VTF por validar`} color="orange"/></section>
          <section className="hero"><div className="hero-copy"><div className="hero-kicker"><span className="tiny-light"/> PLAN ANUAL LOCAL</div><h2>Planificar hoy.<br/><span>Preparar el próximo año.</span></h2><p>Conecta personas, horas y planes de estudio.<br/>Identifica brechas y construye decisiones con respaldo.</p><button className="lime-btn" onClick={()=>changePage('plans')}>Revisar cuadratura <ArrowRight size={17}/></button></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-line"/><div className="art-card art-card-one"><span><CheckCircle2 size={18}/>Plan de estudios</span><div className="fake-line"/><div className="fake-line short"/><div className="fake-chart"><i/><i/><i/><i/><i/><i/></div></div><div className="art-card art-card-two"><span><UsersRound size={16}/>Dotación 2027</span><strong>{fmt(people.length)}</strong><small>personas en planificación</small><div className="fake-progress"><i/></div></div><div className="art-bubble"><Check size={20}/></div><div className="hero-watermark">2027</div></div></section>
          <div className="dashboard-grid"><section className="panel modality-panel"><div className="panel-heading"><div><h2>Una mirada por modalidad</h2><p>Personas en el escenario de planificación</p></div><span className="light-label">2027</span></div><div className="modality-chart"><div className="donut" style={{background:donutGradient}}><div><small>Dotación total</small><strong>{fmt(people.length)}</strong><span>personas</span></div></div><div className="legend">{['Escuela regular','Liceo y TP','Jardín VTF','Especial y rural'].map((m,i)=>{const n=people.filter(p=>{const mode=state.schools.find(s=>s.id===p.schoolId)?.modality;return i===0?mode==='Escuela regular':i===1?['Liceo','Técnico profesional'].includes(mode):i===2?mode==='Jardín VTF':['Escuela especial','Microcentro'].includes(mode);}).length;return <div key={m}><span className={`legend-dot tone-${i}`}/><span>{m}</span><strong>{fmt(n)}</strong></div>;})}</div></div><div className="panel-footer"><span><ShieldCheck size={15}/>Todos los datos de esta demo son ficticios</span><button onClick={()=>changePage('people')}>Explorar dotación <ArrowUpRight size={16}/></button></div></section>
          <section className="panel gap-panel"><div className="panel-heading"><div><h2>Horas que necesitan atención</h2><p>Diferencia entre asignación y plan de estudios</p></div><span className="icon-surface"><TrendingUp size={19}/></span></div><div className="gap-chart">{scoped.filter(s=>s.modality!=='Jardín VTF').slice(0,5).map(s=><button className="gap-row" key={s.id} onClick={()=>goPlan(s.id)}><span title={s.name}>{s.name.replace('Escuela ','')}</span><div className="gap-track"><i className={s.gap>=0?'positive':'negative'} style={{width:`${Math.max(4,Math.min(100,Math.abs(s.gap)/400*100))}%`}}/></div><strong className={s.gap>=0?'text-teal':'text-amber'}>{s.gap>0?'+':''}{fmt(s.gap)}<small> h</small></strong></button>)}</div><div className="chart-legend"><span><i className="positive"/>Excedente</span><span><i className="negative"/>Déficit</span><small>Horas pedagógicas de 45 min</small></div><div className="panel-footer"><span>Cálculo según parámetros del escenario</span><button onClick={()=>changePage('plans')}>Ver cuadratura <ArrowUpRight size={16}/></button></div></section></div>
          <section className="panel"><div className="panel-heading"><div><h2>Establecimientos en foco</h2><p>Una revisión rápida de la dotación y sus brechas</p></div><button className="text-btn" onClick={()=>changePage('schools')}>Ver todos <ArrowRight size={16}/></button></div><SchoolTable rows={scoped.slice(0,5)} open={s=>setModal({type:'school',school:s})} goPlan={goPlan}/></section>
        </>}

        {page==='schools'&&<>
          <section className="small-stats"><span><strong>{scoped.length}</strong> unidades de gestión</span><span><strong>{scoped.filter(s=>s.modality==='Jardín VTF').length}</strong> jardines VTF</span><span><strong>{scoped.filter(s=>s.modality==='Microcentro').reduce((a,s)=>a+s.ruralMembers.length,0)}</strong> escuelas rurales en microcentros</span></section>
          <div className="toolbar"><SearchBox value={query} change={setQuery} placeholder="Buscar establecimiento o comuna"/><ModeSelect value={modality} change={setModality}/>{exportButtons}</div>
          <section className="panel"><div className="panel-heading"><div><h2>Establecimientos y microcentros</h2><p>{visibleSchools.length} unidades · nombres y matrículas ficticias</p></div><span className="light-label">PLAN 2027</span></div><SchoolTable rows={visibleSchools} open={s=>setModal({type:'school',school:s})} goPlan={goPlan}/></section>
        </>}

        {page==='people'&&<>
          <div className="toolbar"><SearchBox value={query} change={setQuery} placeholder="Buscar persona, cargo o establecimiento"/><select aria-label="Tipo de personal" value={personType} onChange={e=>setPersonType(e.target.value)}><option>Todo el personal</option><option>Docente</option><option>Asistente</option></select><ModeSelect value={modality} change={setModality}/>{exportButtons}</div>
          <section className="panel"><div className="panel-heading"><div><h2>Maestro de personal</h2><p>{fmt(filteredPeople.length)} personas · horas contractuales de 60 min / lectivas de 45 min</p></div><button className="primary-btn" onClick={()=>changePage('import')}><Plus size={17}/>Importar personas</button></div><div className="table-scroll"><table><thead><tr><th>PERSONA / ID DEMO</th><th>ESTABLECIMIENTO</th><th>CARGO</th><th>CONTRATO</th><th>LECTIVAS</th><th>FINANCIA.</th><th>PROYECCIÓN</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{filteredPeople.slice((personPage-1)*20,personPage*20).map(p=>{const s=state.schools.find(s=>s.id===p.schoolId);const check=teacherCheck(p,s);return <tr key={p.id}><td><div className="person-cell"><span className="mini-avatar">{p.name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><div><strong>{p.name}</strong><small>{p.id} {p.protection&&'· '+p.protection}</small></div></div></td><td><span className="truncate" title={s.name}>{s.name}</span><small>{s.modality}</small></td><td>{p.role}<small>{p.type}</small></td><td><strong>{p.contractHours} h</strong><small>{p.contract}</small></td><td className={p.type==='Docente'&&check.excess>0?'text-amber':''}>{p.type==='Docente'?`${fmt(p.assignedPed)} h`:'—'}{p.type==='Docente'&&check.excess>0&&<small>Sobrecarga +{fmt(check.excess)}</small>}</td><td><span className="funding">{p.funding}</span></td><td><span className="projection">{p.projection}</span></td><td><div className="row-actions"><button className="icon-btn" aria-label={`Editar ${p.id}`} onClick={()=>setModal({type:'person',person:p})}><Pencil size={15}/></button><button className="icon-btn" aria-label={`Descargar ficha ${p.id}`} disabled={busy} onClick={()=>exportIndividual(p)}><FileText size={16}/></button></div></td></tr>;})}</tbody></table>{!filteredPeople.length&&<Empty/>}</div><div className="pagination"><span>Mostrando {filteredPeople.length?((personPage-1)*20+1):0}–{Math.min(personPage*20,filteredPeople.length)} de {fmt(filteredPeople.length)}</span><div><button disabled={personPage===1} onClick={()=>setPersonPage(p=>p-1)}><ArrowLeft size={15}/>Anterior</button><span>{personPage} / {Math.max(1,Math.ceil(filteredPeople.length/20))}</span><button disabled={personPage*20>=filteredPeople.length} onClick={()=>setPersonPage(p=>p+1)}>Siguiente<ArrowRight size={15}/></button></div></div></section>
        </>}

        {page==='plans'&&<>
          <div className="toolbar"><select className="school-select" aria-label="Establecimiento para cuadratura" value={selectedSchool} onChange={e=>setSelectedSchool(e.target.value)}>{(scope==='all'?state.schools:state.schools.filter(s=>s.id===selectedSchool)).map(s=><option key={s.id} value={s.id}>{s.name} · {s.modality}</option>)}</select><button className="secondary-btn" onClick={()=>setModal({type:'school',school:summary})}><SlidersHorizontal size={16}/>Parámetros</button>{exportButtons}</div>
          <div className="institution-header"><span className="school-icon large"><ModeIcon mode={school.modality} size={26}/></span><div><h2>{school.name}</h2><p>{school.id} · {school.commune} · {school.modality}</p></div><Status value={summary.status}/></div>
          {school.modality==='Jardín VTF'?<VtfPanel school={school} summary={summary} edit={()=>setModal({type:'school',school:summary})}/>:<>
            <section className="kpis plan-kpis"><Kpi icon={BookOpen} title="Horas requeridas" value={fmt(summary.required)} footer="Horas pedagógicas semanales (45 min)" color="teal"/><Kpi icon={UsersRound} title="Horas asignadas" value={fmt(summary.assigned)} footer={`${summary.teachers} docentes en este establecimiento`} color="blue"/><Kpi icon={TrendingUp} title={summary.gap<0?'Déficit de asignación':'Excedente de asignación'} value={fmt(Math.abs(summary.gap))} footer="Asignadas − requeridas · horas de 45 min" color={summary.gap<0?'orange':'teal'}/><Kpi icon={Clock3} title="Capacidad lectiva máxima" value={fmt(summary.capacity)} footer={`Ratio configurado ${fmt(school.lectiveRatio*100)}/${fmt((1-school.lectiveRatio)*100)} · horas de 45 min`} color="purple"/></section>
            <div className="info-banner"><CircleHelp size={18}/><div><strong>Cálculos trazables, con unidades explícitas.</strong><span>Requeridas = cursos × horas pedagógicas por curso. Capacidad = horas contractuales × proporción lectiva × 60/45. La aplicabilidad de cada regla debe validarse antes de usar datos reales.</span></div><button onClick={()=>setModal({type:'rules'})}>Ver reglas<ArrowUpRight size={15}/></button></div>
            {school.modality==='Técnico profesional'&&<div className="mode-banner"><BriefcaseBusiness size={19}/>Formación general y especialidad técnico-profesional se planifican por separado.</div>}
            {school.modality==='Escuela especial'&&<div className="mode-banner"><GraduationCap size={19}/>Escuela especial: plan de aprendizaje integral y talleres. Adecuación curricular pendiente de validar.</div>}
            {school.modality==='Microcentro'&&<div className="mode-banner"><Layers size={19}/><div><strong>{school.ruralMembers.length} escuelas rurales multigrado agrupadas</strong><small>{school.ruralMembers.join(' · ')}</small></div></div>}
            <section className="panel"><div className="panel-heading"><div><h2>{school.modality==='Microcentro'?'Plan agrupado del microcentro':'Plan de estudios del establecimiento'}</h2><p>Escenario ficticio editable · no corresponde a una malla oficial MINEDUC</p></div><button className="primary-btn" onClick={()=>setModal({type:'plan',plan:{id:crypto.randomUUID(),schoolId:school.id,subject:'',groups:1,hoursPerGroup:1},isNew:true})}><Plus size={16}/>Agregar asignatura</button></div><div className="table-scroll"><table><thead><tr><th>ASIGNATURA / COMPONENTE</th><th>CURSOS O GRUPOS</th><th>HORAS POR CURSO</th><th>TOTAL REQUERIDO</th><th>ACCIÓN</th></tr></thead><tbody>{state.plans.filter(p=>p.schoolId===school.id).map(p=><tr key={p.id}><td><strong>{p.subject}</strong></td><td>{p.groups}</td><td>{p.hoursPerGroup} h pedagógicas</td><td><strong>{fmt(p.groups*p.hoursPerGroup)} h</strong></td><td><button className="text-btn" onClick={()=>setModal({type:'plan',plan:p})}><Pencil size={14}/>Editar</button></td></tr>)}</tbody><tfoot><tr><td colSpan="3">Total de horas pedagógicas requeridas</td><td colSpan="2">{fmt(summary.required)} h</td></tr></tfoot></table></div></section>
          </>}
          <section className="panel projection-panel"><div><span className="eyebrow">PROYECCIÓN 2027</span><h2>{school.projection}</h2><p>{school.justification||'Sin cambios de dotación justificados en este escenario.'}</p></div><button className="secondary-btn" onClick={()=>setModal({type:'school',school:summary})}>Registrar decisión <Pencil size={15}/></button><button className="text-btn" onClick={()=>goPeople(school.id)}>Ver personal <ArrowRight size={16}/></button></section>
        </>}

        {page==='import'&&<ImportPanel state={state} commit={commit} notify={setNotice} goPeople={()=>{setScope('all');changePage('people');}} readOnly={scope!=='all'}/>}

        {page==='reassign'&&<ReassignPanel stats={stats} state={state} commit={commit} notify={setNotice} readOnly={scope!=='all'}/>}

        {page==='history'&&<><div className="toolbar"><div className="info-inline"><ShieldCheck size={18}/>Registro local del escenario; no es una auditoría de producción.</div><button className="secondary-btn" onClick={()=>saveDownload('bitacora-demo.csv',serializeCSV(events.map(e=>({Fecha:e.date,Accion:e.action,Detalle:e.detail,Autor:e.author}))))}><Download size={16}/>Exportar bitácora</button><button className="secondary-btn" onClick={()=>setModal({type:'reset'})}><RotateCcw size={16}/>Restablecer demo</button></div><section className="panel"><div className="panel-heading"><div><h2>Historial de decisiones</h2><p>{events.length} eventos en este navegador</p></div></div><div className="timeline">{events.map(e=><article key={e.id}><span className="timeline-icon"><History size={17}/></span><div><h3>{e.action}</h3><p>{e.detail}</p><small>{e.author} · {new Date(e.date).toLocaleString('es-CL')}</small></div><span className="badge neutral">Registrado</span></article>)}</div></section></>}
        <footer className="main-footer"><span>CMEstudios <span>·</span> Gestión de dotación escolar</span><span>Demo funcional · datos locales en este navegador</span></footer>
      </div>
    </main>
    {notice&&<div className="toast" role="status"><CheckCircle2 size={19}/>{notice}<button onClick={()=>setNotice('')} aria-label="Cerrar aviso"><X size={16}/></button></div>}
    {modal?.type==='person'&&<EditPerson key={modal.person.id} person={modal.person} schools={scope==='all'?state.schools:state.schools.filter(s=>s.id===selectedSchool)} close={()=>setModal(null)} save={p=>{commit(prev=>({...prev,staff:prev.staff.map(x=>x.id===p.id?p:x)}),'Ajuste de dotación',`${p.name} (${p.id}): ${p.contractHours} h contrato, ${p.assignedPed} h lectivas; ${p.projection}. Motivo: ${p.justification}`);setModal(null);setNotice('Dotación actualizada. La cuadratura se recalculó.');}}/>}
    {modal?.type==='school'&&<EditSchool key={modal.school.id} school={state.schools.find(s=>s.id===modal.school.id)} summary={stats.find(s=>s.id===modal.school.id)} close={()=>setModal(null)} save={s=>{commit(prev=>({...prev,schools:prev.schools.map(x=>x.id===s.id?s:x)}),'Parámetros y proyección actualizados',`${s.name}: ratio ${s.lectiveRatio*100}%, proyección ${s.projection}. ${s.justification}`);setModal(null);setNotice('Parámetros guardados. Se recalcularon las métricas.');}} goPlan={()=>{goPlan(modal.school.id);setModal(null);}}/>}
    {modal?.type==='plan'&&<EditPlan plan={modal.plan} isNew={modal.isNew} close={()=>setModal(null)} save={(p,reason)=>{commit(prev=>({...prev,plans:modal.isNew?[...prev.plans,p]:prev.plans.map(x=>x.id===p.id?p:x)}),modal.isNew?'Asignatura incorporada':'Plan de estudios actualizado',`${school.name}: ${p.subject}, ${p.groups} cursos × ${p.hoursPerGroup} h. Motivo: ${reason}`);setModal(null);setNotice('Plan guardado. Cuadratura recalculada.');}}/>}
    {modal?.type==='rules'&&<Dialog title="Alcance y reglas de la demo" subtitle="Qué funciona hoy y qué falta validar" close={()=>setModal(null)} wide><div className="dialog-body rules-copy"><p><strong>Funciona:</strong> importación CSV validada, asignación de personal, ajustes con justificación, planes editables, cálculo de brechas, vistas por modalidad, reportes CSV/Excel/PDF y bitácora local.</p><h3>Horas y proporciones</h3><p>El contrato usa horas de 60 minutos y el plan horas pedagógicas de 45 minutos. Capacidad lectiva = horas de contrato × proporción configurada × 60/45. La demo permite 65/35 o 60/40 por establecimiento. La aplicabilidad debe determinarse por docente y normativa antes de producción; no todos los cargos tienen horas de aula.</p><h3>Jardines VTF</h3><p>Los coeficientes no vienen fijados en las bases. Se configuran como escenario y se comparan con matrícula, educadoras y técnicas; no se presentan como coeficientes legales verificados. Quedan pendientes las reglas por nivel y edad.</p><h3>Condiciones pendientes</h3><p>Validar reglas PIE/NEE, horas gremiales, fueros, fuentes de financiamiento y modalidades especiales. Adaptar reportes a layouts oficiales MINEDUC y DEP. Implementar permisos reales, autenticación, 2FA, servidor, respaldos y soporte; hoy las vistas son simuladas y los datos se guardan en este navegador.</p></div><div className="dialog-actions"><button className="primary-btn" onClick={()=>setModal(null)}>Entendido</button></div></Dialog>}
    {modal?.type==='guide'&&<Dialog title="Un recorrido de 4 minutos" subtitle="Cinco capacidades exigidas para el Anexo 7" close={()=>setModal(null)}><div className="dialog-body guide-steps">{[['00:00','Vista general','Dashboard con docentes, asistentes y cobertura.'],['00:40','Importar datos','Carga CSV, validación y confirmación de cambios.'],['01:30','Modalidades','Escuela regular, TP, jardín VTF y microcentro.'],['02:20','Cuadratura','Edita un plan o una jornada y muestra el recálculo.'],['03:15','Cierre','Exporta un reporte y revisa la bitácora.']].map(([time,title,desc])=><div key={time}><span>{time}</span><section><h3>{title}</h3><p>{desc}</p></section></div>)}</div><div className="dialog-actions"><button className="primary-btn" onClick={()=>{setModal(null);changePage('overview');}}>Comenzar recorrido <ArrowRight size={16}/></button></div></Dialog>}
    {modal?.type==='alerts'&&<Dialog title="Alertas de planificación" subtitle="Resultados según parámetros del escenario" close={()=>setModal(null)}><div className="dialog-body"><div className="warning-banner"><AlertTriangle size={18}/>{deficits.length} unidades con déficit · {overloads} sobrecargas.</div>{scoped.filter(s=>s.status==='Déficit'||s.status==='Sobrecarga'||s.status==='Por validar').slice(0,12).map(s=><button className="alert-item" key={s.id} onClick={()=>{goPlan(s.id);setModal(null);}}><div><strong>{s.name}</strong><small>{s.modality==='Jardín VTF'?'Coeficientes VTF pendientes de validación':`${fmt(s.gap)} h pedagógicas de diferencia`}</small></div><Status value={s.status}/><ArrowUpRight size={16}/></button>)}</div></Dialog>}
    {modal?.type==='reset'&&<Dialog title="¿Restablecer el escenario?" subtitle="Se eliminarán ajustes, importaciones y bitácora de esta demo." close={()=>setModal(null)}><div className="dialog-body"><p>Los archivos que ya descargaste se conservan. Esta acción recupera los 2.200 registros ficticios iniciales.</p></div><div className="dialog-actions"><button className="secondary-btn" onClick={()=>setModal(null)}>Cancelar</button><button className="primary-btn" onClick={()=>{setState(createSeed());setModal(null);setNotice('Escenario inicial restablecido.');}}>Restablecer demo</button></div></Dialog>}
  </div>;
}

function Kpi({icon:Icon,title,value,footer,color}) {return <article className="kpi"><div className="kpi-top"><span>{title}</span><span className={`kpi-icon ${color}`}><Icon size={19}/></span></div><strong>{value}</strong><p>{footer}</p></article>;}
function SearchBox({value,change,placeholder}) {return <label className="search"><Search size={17}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>change(e.target.value)}/>{value&&<button aria-label="Limpiar búsqueda" onClick={()=>change('')}><X size={14}/></button>}</label>;}
function ModeSelect({value,change}) {return <select aria-label="Filtrar modalidad" value={value} onChange={e=>change(e.target.value)}><option>Todas las modalidades</option>{MODALITIES.map(m=><option key={m}>{m}</option>)}</select>;}
function Empty() {return <div className="empty"><Search size={28}/><h3>No hay resultados</h3><p>Prueba otra búsqueda o cambia los filtros.</p></div>;}
function SchoolTable({rows,open,goPlan}) {return <div className="table-scroll"><table><thead><tr><th>ESTABLECIMIENTO</th><th>MODALIDAD</th><th>DOCENTES</th><th>ASISTENTES</th><th>BRECHA LECTIVA</th><th>ESTADO</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><button className="school-name" onClick={()=>open(s)}><span className="school-icon"><ModeIcon mode={s.modality}/></span><span><strong>{s.name}</strong><small>{s.commune} · {s.id}</small></span></button></td><td>{s.modality}</td><td>{s.teachers}</td><td>{s.assistants}</td><td className={s.gap<0?'text-amber':'text-teal'}>{s.modality==='Jardín VTF'?<span className="text-muted">Por coeficientes</span>:<><strong>{s.gap>0?'+':''}{fmt(s.gap)} h</strong><small>pedagógicas</small></>}</td><td><Status value={s.status}/></td><td><button className="icon-btn" aria-label={`Ver cuadratura ${s.name}`} onClick={()=>goPlan(s.id)}><ArrowUpRight size={18}/></button></td></tr>)}</tbody></table>{!rows.length&&<Empty/>}</div>;}
function VtfPanel({school,summary,edit}) {return <><div className="info-banner"><Sprout size={21}/><div><strong>Gestión VTF por matrícula y coeficientes de atención.</strong><span>Este módulo compara personas requeridas y disponibles; no utiliza cuadratura curricular de horas. Los coeficientes son parámetros de escenario pendientes de validación por nivel.</span></div></div><section className="kpis"><Kpi icon={UsersRound} title="Matrícula de escenario" value={school.enrollment} footer="Niñas y niños · cifra ficticia" color="teal"/><Kpi icon={GraduationCap} title="Educadoras disponibles" value={summary.educators} footer={summary.needEducators===null?'Coeficiente por validar':`Requeridas: ${summary.needEducators} según escenario`} color="blue"/><Kpi icon={BriefcaseBusiness} title="Técnicas disponibles" value={summary.technicians} footer={summary.needTechnicians===null?'Coeficiente por validar':`Requeridas: ${summary.needTechnicians} según escenario`} color="purple"/><Kpi icon={SlidersHorizontal} title="Coeficientes de atención" value={summary.vtfConfigured?'Configurados':'Pendientes'} footer="Validar aplicabilidad según nivel y edad" color="orange"/></section><section className="panel vtf-card"><span className="school-icon large"><Sprout size={29}/></span><div><h2>{summary.vtfConfigured?'Escenario de coeficientes activo':'Configura un escenario de atención'}</h2><p>{summary.vtfConfigured?`Una educadora por ${school.educatorPerChildren} niños y una técnica por ${school.technicianPerChildren}. Se redondean hacia arriba los cargos requeridos.`:'Las bases no especifican los valores de los coeficientes. Puedes ensayar valores, identificados como escenario y no como validación normativa.'}</p></div><button className="primary-btn" onClick={edit}>Configurar <SlidersHorizontal size={16}/></button></section></>;}

function EditPerson({person,schools,close,save}) {
  const [p,setP]=useState({...person});const [error,setError]=useState('');const school=schools.find(s=>s.id===p.schoolId);const check=teacherCheck(p,school);
  const field=(key,val)=>setP(prev=>({...prev,[key]:val}));
  const submit=e=>{e.preventDefault();if(!p.justification.trim())return setError('Escribe una justificación para registrar el cambio.');if(!Number.isFinite(p.contractHours)||p.contractHours<=0||p.contractHours>44||!Number.isFinite(p.assignedPed)||p.assignedPed<0)return setError('Revisa las horas ingresadas.');save({...p,assignedPed:p.type==='Asistente'?0:p.assignedPed});};
  return <Dialog title="Ajustar dotación" subtitle={`${person.name} · ${person.id}`} close={close}><form onSubmit={submit}><div className="dialog-body form-grid"><label className="full">Establecimiento<select value={p.schoolId} onChange={e=>field('schoolId',e.target.value)}>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Horas de contrato (60 min)<input type="number" min="0.1" max="44" step="0.1" required value={p.contractHours} onChange={e=>field('contractHours',e.target.value===''?NaN:Number(e.target.value))}/></label><label>Lectivas asignadas (45 min)<input type="number" min="0" step="0.1" required disabled={p.type==='Asistente'} value={p.assignedPed} onChange={e=>field('assignedPed',e.target.value===''?NaN:Number(e.target.value))}/></label><label>Financiamiento<select value={p.funding} onChange={e=>field('funding',e.target.value)}>{['General','SEP','PIE'].map(v=><option key={v}>{v}</option>)}</select></label><label>Proyección<select value={p.projection} onChange={e=>field('projection',e.target.value)}>{['Mantención','Aumento','Disminución','No renovación'].map(v=><option key={v}>{v}</option>)}</select></label><label className="full">Justificación del ajuste<textarea required value={p.justification} onChange={e=>field('justification',e.target.value)} placeholder="Ej.: ajuste de escenario por cambio de matrícula"/></label>{p.type==='Docente'&&<div className={`full ${check.excess>0?'warning-banner':'info-inline'}`}><AlertTriangle size={17}/>{check.excess>0?`Sobrecarga: ${fmt(check.excess)} h sobre el máximo configurado.`:`Capacidad lectiva configurada: ${fmt(check.capacity)} h pedagógicas.`}</div>}{error&&<p className="error-text full" role="alert">{error}</p>}</div><div className="dialog-actions"><button type="button" className="secondary-btn" onClick={close}>Cancelar</button><button className="primary-btn" type="submit">Guardar y recalcular <Check size={16}/></button></div></form></Dialog>;
}

function EditSchool({school,summary,close,save,goPlan}) {
  const [s,setS]=useState({...school});const [error,setError]=useState('');const vtf=s.modality==='Jardín VTF';
  const field=(key,val)=>setS(prev=>({...prev,[key]:val}));
  const submit=e=>{e.preventDefault();if(!s.justification.trim())return setError('Registra la justificación de los parámetros o de la proyección.');if(vtf&&((s.educatorPerChildren!==null&&(!Number.isInteger(s.educatorPerChildren)||s.educatorPerChildren<=0))||(s.technicianPerChildren!==null&&(!Number.isInteger(s.technicianPerChildren)||s.technicianPerChildren<=0))))return setError('Los coeficientes deben ser enteros positivos.');save(s);};
  return <Dialog title={school.name} subtitle={`${school.modality} · ${school.commune} · ${school.id}`} close={close}><form onSubmit={submit}><div className="dialog-body form-grid"><div className="full mini-summary"><span><strong>{summary.teachers}</strong> docentes</span><span><strong>{summary.assistants}</strong> asistentes</span><span><strong>{s.enrollment}</strong> matrícula ficticia</span></div>{vtf?<><label>Niños por educadora (escenario)<input type="number" min="1" step="1" value={s.educatorPerChildren??''} onChange={e=>field('educatorPerChildren',e.target.value?Number(e.target.value):null)} placeholder="Por validar"/></label><label>Niños por técnica (escenario)<input type="number" min="1" step="1" value={s.technicianPerChildren??''} onChange={e=>field('technicianPerChildren',e.target.value?Number(e.target.value):null)} placeholder="Por validar"/></label><p className="full field-help">Valores de simulación. Las reglas legales por nivel y edad deben validarse.</p></>:<label className="full">Proporción lectiva / no lectiva del escenario<select value={s.lectiveRatio} onChange={e=>field('lectiveRatio',Number(e.target.value))}><option value="0.65">65% lectiva / 35% no lectiva</option><option value="0.6">60% lectiva / 40% no lectiva</option></select><small>Parámetro simplificado por establecimiento; aplicabilidad por docente pendiente de validar.</small></label>}<label className="full">Proyección 2027<select value={s.projection} onChange={e=>field('projection',e.target.value)}>{['Mantención','Aumento','Disminución'].map(v=><option key={v}>{v}</option>)}</select></label><label className="full">Justificación técnico-pedagógica<textarea required value={s.justification} onChange={e=>field('justification',e.target.value)} placeholder="Describe matrícula, plan de estudios o necesidades del escenario"/></label>{s.ruralMembers.length>0&&<div className="full field-help"><strong>Escuelas rurales agrupadas:</strong> {s.ruralMembers.join(', ')}</div>}{error&&<p className="error-text full" role="alert">{error}</p>}</div><div className="dialog-actions"><button type="button" className="text-btn" onClick={goPlan}>Ver cuadratura <ArrowUpRight size={15}/></button><button type="button" className="secondary-btn" onClick={close}>Cancelar</button><button className="primary-btn">Guardar parámetros</button></div></form></Dialog>;
}

function EditPlan({plan,isNew,close,save}) {const [p,setP]=useState({...plan});const [reason,setReason]=useState('');const [error,setError]=useState('');return <Dialog title={isNew?'Agregar asignatura':'Editar plan de estudios'} subtitle="El cambio recalcula las horas requeridas del establecimiento." close={close}><form onSubmit={e=>{e.preventDefault();if(!p.subject.trim()||!reason.trim()||!Number.isInteger(p.groups)||p.groups<1||!Number.isFinite(p.hoursPerGroup)||p.hoursPerGroup<0)return setError('Completa nombre, cursos, horas y justificación.');save(p,reason);}}><div className="dialog-body form-grid"><label className="full">Asignatura o componente<input required value={p.subject} onChange={e=>setP({...p,subject:e.target.value})}/></label><label>Cursos o grupos<input type="number" required min="1" max="100" step="1" value={p.groups} onChange={e=>setP({...p,groups:e.target.value===''?NaN:Number(e.target.value)})}/></label><label>Horas pedagógicas por curso<input type="number" required min="0" max="100" step="0.1" value={p.hoursPerGroup} onChange={e=>setP({...p,hoursPerGroup:e.target.value===''?NaN:Number(e.target.value)})}/></label><div className="full calculation-preview">Total requerido <strong>{fmt(p.groups*p.hoursPerGroup)} h pedagógicas</strong></div><label className="full">Justificación<textarea required value={reason} onChange={e=>setReason(e.target.value)} placeholder="Describe el ajuste de este escenario"/></label>{error&&<p className="error-text full" role="alert">{error}</p>}</div><div className="dialog-actions"><button type="button" className="secondary-btn" onClick={close}>Cancelar</button><button className="primary-btn">Guardar y recalcular <Check size={16}/></button></div></form></Dialog>;}

function ImportPanel({state,commit,notify,goPeople,readOnly}) {
  const [candidate,setCandidate]=useState(null);const [error,setError]=useState('');const [drag,setDrag]=useState(false);const [done,setDone]=useState(null);const fileRef=useRef();
  const result=useMemo(()=>candidate?validateImport(candidate.rows,state):null,[candidate,state]);
  const prepare=(text,name)=>{try{const rows=parseCSV(text);if(rows.length>10000)throw new Error('Máximo de demostración: 10.000 filas.');setCandidate({rows,name});setError('');setDone(null);}catch(e){setError(e.message);setCandidate(null);setDone(null);}};
  const load=async file=>{if(!file)return; if(!file.name.toLowerCase().endsWith('.csv')){setError('Selecciona un archivo .csv.');return;}if(file.size>5*1024*1024){setError('El archivo supera el máximo de 5 MB.');return;}try{prepare(await file.text(),file.name);}catch{setError('No se pudo leer el archivo.');}};
  const confirm=()=>{if(!result||result.errors.length||readOnly)return;const existing=new Set(state.staff.map(p=>p.id));const updated=result.people.filter(p=>existing.has(p.id)).length;const added=result.people.length-updated;commit(prev=>applyImport(prev,result.people),'Maestro CSV importado',`${candidate.name}: ${added} personas nuevas y ${updated} actualizadas por ID. Todas las filas validadas antes de aplicar.`);setDone({added,updated});setCandidate(null);notify('Importación completada. Dashboard y cuadratura actualizados.');};
  return <div className="import-layout"><div>{readOnly&&<div className="warning-banner"><ShieldCheck size={17}/>La importación está disponible en la vista Sostenedor. Cambia la vista superior para continuar.</div>}<section className="panel import-card"><div className="panel-heading"><div><h2>Importar maestro de personal</h2><p>Archivo CSV · separado por punto y coma o coma</p></div><span className="icon-surface"><FileSpreadsheet size={21}/></span></div><div className={`dropzone ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(!readOnly)load(e.dataTransfer.files[0]);}}><span className="upload-icon"><UploadCloud size={31}/></span><h3>Arrastra tu archivo aquí</h3><p>O selecciónalo desde tu equipo. Máximo 5 MB.</p><input ref={fileRef} aria-label="Archivo CSV del maestro" type="file" accept=".csv,text/csv" disabled={readOnly} onChange={e=>{load(e.target.files[0]);e.target.value='';}}/><button disabled={readOnly} className="primary-btn" onClick={()=>fileRef.current.click()}>Seleccionar CSV <Plus size={16}/></button></div><div className="sample-actions"><button className="text-btn" onClick={()=>saveDownload('maestro-personal-ejemplo.csv',sampleImport())}><Download size={16}/>Descargar CSV de ejemplo</button><button disabled={readOnly} className="text-btn" onClick={()=>prepare(sampleImport(),'maestro-personal-ejemplo.csv')}>Probar archivo de ejemplo <ArrowRight size={16}/></button></div></section>
    {error&&<div className="warning-banner" role="alert"><AlertTriangle size={19}/>{error}</div>}
    {candidate&&<section className="panel preview-card"><div className="panel-heading"><div><h2>Revisión antes de importar</h2><p>{candidate.name} · {candidate.rows.length} filas</p></div><span className={`badge ${result.errors.length?'amber':'green'}`}>{result.errors.length?'Requiere correcciones':'Validación completa'}</span></div>{result.errors.length?<div className="validation-errors" role="alert"><strong>No se aplicó ningún cambio.</strong><ul>{result.errors.slice(0,15).map((e,i)=><li key={i}>{e}</li>)}</ul>{result.errors.length>15&&<p>Y {result.errors.length-15} errores adicionales.</p>}</div>:<><div className="mini-summary"><span><strong>{result.people.filter(p=>!state.staff.some(s=>s.id===p.id)).length}</strong> nuevos</span><span><strong>{result.people.filter(p=>state.staff.some(s=>s.id===p.id)).length}</strong> actualizados por ID</span></div><div className="table-scroll"><table><thead><tr><th>ID</th><th>NOMBRE</th><th>ESTABLECIMIENTO</th><th>HORAS</th></tr></thead><tbody>{result.people.slice(0,8).map(p=><tr key={p.id}><td>{p.id}</td><td>{p.name}</td><td>{p.schoolId}</td><td>{p.contractHours} h contrato</td></tr>)}</tbody></table></div><p className="field-help padded">Los IDs existentes se actualizan; las personas nuevas se agregan. Los registros que no aparecen en el archivo se conservan. Las posibles sobrecargas quedan visibles como alertas.</p></>}<div className="dialog-actions"><button className="secondary-btn" onClick={()=>setCandidate(null)}>Descartar archivo</button><button className="primary-btn" disabled={result.errors.length>0||readOnly} onClick={confirm}>Confirmar importación <Check size={17}/></button></div></section>}
    {done&&<section className="panel import-success"><CheckCircle2 size={35}/><h2>Datos incorporados</h2><p>{done.added} personas nuevas y {done.updated} actualizadas. El cambio quedó en la bitácora.</p><button className="primary-btn" onClick={goPeople}>Revisar dotación <ArrowRight size={16}/></button></section>}</div><aside className="import-aside"><span className="eyebrow">ANTES DE IMPORTAR</span><h2>Un maestro.<br/>Una fuente de verdad.</h2><p>Esta demo utiliza una estructura propia. Adaptaremos el mapeo al maestro real cuando el SLEP entregue sus insumos.</p><div className="import-check"><CheckCircle2 size={18}/><div><strong>Identificación por ID</strong><p>En la demo usamos IDs ficticios; no RUT de personas reales.</p></div></div><div className="import-check"><CheckCircle2 size={18}/><div><strong>Asignación por establecimiento</strong><p>Utiliza EST-001 a EST-056, disponibles en Establecimientos.</p></div></div><div className="import-check"><CheckCircle2 size={18}/><div><strong>Sin cambios parciales</strong><p>Si una fila tiene errores, se bloquea el archivo completo.</p></div></div><div className="import-check"><CheckCircle2 size={18}/><div><strong>Unidades de tiempo</strong><p>Contrato en horas de 60 min; lectivas en horas de 45 min.</p></div></div><div className="column-note"><strong>Columnas obligatorias</strong><code>id · nombre · establecimiento_id · tipo · cargo · horas_contrato · horas_lectivas_pedagogicas · financiamiento · contrato</code></div></aside></div>;
}

function ReassignPanel({stats,state,commit,notify,readOnly}) {
  const eligible=stats.filter(s=>s.modality!=='Jardín VTF'&&s.status!=='Por validar');
  const surplus=eligible.filter(s=>s.gap>0.01).sort((a,b)=>b.gap-a.gap);
  const deficit=eligible.filter(s=>s.gap<-0.01).sort((a,b)=>a.gap-b.gap);
  const suggestions=useMemo(()=>suggestReassignments(stats,state.staff),[stats,state.staff]);
  const [skip,setSkip]=useState(()=>new Set());
  const [reason,setReason]=useState('');
  const [error,setError]=useState('');
  const [from,setFrom]=useState('');const [personId,setPersonId]=useState('');const [to,setTo]=useState('');const [manualReason,setManualReason]=useState('');const [manualError,setManualError]=useState('');
  const chosen=suggestions.filter(m=>!skip.has(m.personId));
  const byId=new Map(stats.map(s=>[s.id,s]));
  const projected=useMemo(()=>{const next=applyReassignments(state,chosen);return state.schools.map(sc=>summarizeSchool(sc,next.staff,next.plans));},[state,chosen]);
  const stillDeficit=projected.filter(s=>s.modality!=='Jardín VTF'&&s.status==='Déficit').length;
  const hoursMoved=chosen.reduce((a,m)=>a+m.hours,0);
  const toggle=id=>setSkip(prev=>{const n=new Set(prev);n.has(id)?n.delete(id):n.add(id);return n;});
  const applyChosen=()=>{
    if(!chosen.length)return setError('Selecciona al menos un movimiento.');
    if(!reason.trim())return setError('Escribe una justificación para registrar la reasignación.');
    commit(prev=>applyReassignments(prev,chosen),'Reasignación de dotación',`${chosen.length} docentes reasignados (${fmt(hoursMoved)} h lectivas): ${chosen.map(m=>`${m.name} (${m.personId}) ${m.fromId}→${m.toId}`).join('; ')}. Motivo: ${reason}`);
    setReason('');setError('');setSkip(new Set());notify(`${chosen.length} reasignaciones aplicadas. La cuadratura se recalculó.`);
  };
  const candidates=state.staff.filter(p=>p.schoolId===from&&movableTeachers(p));
  const person=candidates.find(p=>p.id===personId);
  const src=byId.get(from),dst=byId.get(to);
  const manualOk=person&&dst&&from!==to;
  const applyManual=()=>{
    if(!manualOk)return setManualError('Elige origen, docente y destino distintos.');
    if(!manualReason.trim())return setManualError('Escribe una justificación para registrar el movimiento.');
    commit(prev=>({...prev,staff:prev.staff.map(x=>x.id===person.id?{...x,schoolId:to}:x)}),'Reasignación manual',`${person.name} (${person.id}): ${src.name} → ${dst.name}, ${fmt(person.assignedPed)} h lectivas. Motivo: ${manualReason}`);
    setPersonId('');setManualReason('');setManualError('');notify('Docente reasignado. La cuadratura se recalculó.');
  };
  const SchoolList=({rows,sign})=><div className="table-scroll"><table><thead><tr><th>ESTABLECIMIENTO</th><th>COMUNA</th><th>BRECHA (h ped.)</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.commune}</td><td><strong>{sign}{fmt(Math.abs(s.gap))}</strong></td></tr>)}{!rows.length&&<tr><td colSpan="3">Sin establecimientos.</td></tr>}</tbody></table></div>;
  return <>
    {readOnly&&<div className="warning-banner"><ShieldCheck size={17}/>Las reasignaciones están disponibles en la vista Sostenedor. Cambia la vista superior para aplicarlas.</div>}
    <section className="kpis"><Kpi icon={TrendingUp} title="Excedente total" value={fmt(surplus.reduce((a,s)=>a+s.gap,0))} footer={`${surplus.length} establecimientos · horas pedagógicas`} color="blue"/><Kpi icon={AlertTriangle} title="Déficit total" value={fmt(deficit.reduce((a,s)=>a-s.gap,0))} footer={`${deficit.length} establecimientos · horas pedagógicas`} color="orange"/><Kpi icon={ArrowLeftRight} title="Movimientos sugeridos" value={suggestions.length} footer={`${fmt(suggestions.reduce((a,m)=>a+m.hours,0))} h lectivas por mover`} color="teal"/><Kpi icon={CheckCircle2} title="Déficit tras aplicar" value={stillDeficit} footer="Establecimientos que seguirían en déficit con la selección" color="purple"/></section>
    <div className="info-banner"><CircleHelp size={18}/><div><strong>Cómo se calcula.</strong><span>Se mueven docentes de aula completos con sus horas lectivas. Ningún origen queda en déficit ni el destino se excede. Se priorizan movimientos dentro de la misma comuna. Se excluyen personas con fuero y los Jardines VTF.</span></div></div>
    <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><h2>Con excedente</h2><p>Horas asignadas sobre el plan</p></div></div><SchoolList rows={surplus} sign="+"/></section><section className="panel"><div className="panel-heading"><div><h2>Con déficit</h2><p>Horas del plan sin cubrir</p></div></div><SchoolList rows={deficit} sign="−"/></section></div>
    <section className="panel"><div className="panel-heading"><div><h2>Sugerencias de reasignación</h2><p>{chosen.length} de {suggestions.length} seleccionadas · {fmt(hoursMoved)} h lectivas</p></div></div>
      <div className="table-scroll"><table><thead><tr><th></th><th>DOCENTE</th><th>HORAS LECTIVAS</th><th>ORIGEN</th><th>DESTINO</th><th>COMUNA</th></tr></thead><tbody>{suggestions.map(m=><tr key={m.personId}><td><input type="checkbox" aria-label={`Incluir ${m.name}`} checked={!skip.has(m.personId)} onChange={()=>toggle(m.personId)}/></td><td>{m.name}<br/><small>{m.personId}</small></td><td>{fmt(m.hours)}</td><td>{m.from}</td><td>{m.to}</td><td>{m.sameCommune?'Misma comuna':'Otra comuna'}</td></tr>)}{!suggestions.length&&<tr><td colSpan="6">No hay movimientos posibles con las reglas actuales.</td></tr>}</tbody></table></div>
      {!readOnly&&suggestions.length>0&&<div className="form-grid" style={{padding:16}}><label className="full">Justificación<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ej.: cuadratura 2027 entre establecimientos de la misma comuna"/></label>{error&&<p className="error-text full" role="alert">{error}</p>}<div className="full"><button className="primary-btn" onClick={applyChosen}>Aplicar {chosen.length} reasignaciones <Check size={16}/></button></div></div>}
    </section>
    <section className="panel"><div className="panel-heading"><div><h2>Reasignación manual</h2><p>Mueve un docente de aula específico entre establecimientos</p></div></div>
      <div className="form-grid" style={{padding:16}}>
        <label>Origen<select value={from} onChange={e=>{setFrom(e.target.value);setPersonId('');}}><option value="">Elegir…</option>{eligible.map(s=><option key={s.id} value={s.id}>{s.name} ({s.gap>0?'+':''}{fmt(s.gap)} h)</option>)}</select></label>
        <label>Docente<select value={personId} onChange={e=>setPersonId(e.target.value)} disabled={!from}><option value="">Elegir…</option>{candidates.map(p=><option key={p.id} value={p.id}>{p.name} · {fmt(p.assignedPed)} h</option>)}</select></label>
        <label>Destino<select value={to} onChange={e=>setTo(e.target.value)}><option value="">Elegir…</option>{eligible.filter(s=>s.id!==from).map(s=><option key={s.id} value={s.id}>{s.name} ({s.gap>0?'+':''}{fmt(s.gap)} h)</option>)}</select></label>
        {manualOk&&<div className="full info-inline"><ArrowLeftRight size={17}/>{src.name}: {fmt(src.gap)} → {fmt(round(src.gap-person.assignedPed))} h · {dst.name}: {fmt(dst.gap)} → {fmt(round(dst.gap+person.assignedPed))} h{src.gap-person.assignedPed<-0.01?' · el origen quedaría en déficit':''}</div>}
        <label className="full">Justificación<textarea value={manualReason} onChange={e=>setManualReason(e.target.value)} placeholder="Motivo del movimiento"/></label>
        {manualError&&<p className="error-text full" role="alert">{manualError}</p>}
        <div className="full"><button className="primary-btn" disabled={readOnly} onClick={applyManual}>Mover docente <Check size={16}/></button></div>
      </div></section>
  </>;
}
